### ISSUE TITLE
Feature request: Interactive text highlights

### ISSUE THREAD

**Issue by gsarti** [google-deepmind/treescope#8]
Hi, thanks for making `treescope` a stand-alone package! I am currently working towards integrating it in our Inseq toolkit for input attribution visualization here: inseq-team/inseq#283

I was wondering how feasible it would be to have customizable interactive `text_on_color` elements. Currently, we can present highlights over a input text for every generation step, but this can become very lengthy for long output sequences:

<img width="492" alt="image" src="https://github.com/user-attachments/assets/accadec3-4d74-4016-a494-2b28a63f9b5a">

An idea to make the visualization less overwhelming would be to have a way to dynamically change the highlighting over the input tokens by hovering/clicking on a generated token, so that only two sequences (input tokens, output tokens) linked by a 2D matrix of values would be needed (similar to the interactive component used by the [`ecco`](https://github.com/jalammar/ecco) library.

Would this be feasible using `treescope` in its current state, or would it be possible to add a similar feature in the future?

**Comment by gsarti** [comment]
Hi @danieldjohnson, thanks for your reply!

Ecco is currently not maintained, and it uses a custom JS library for visualization purposes. Provided that we will use `treescope` regardless in Inseq, I was asking because it would have been a convenient addition without handling further imports. Thanks anyways!

**Comment by gsarti** [comment]
I thought a possible option would be to render the generated text inline as a sequence of tokens, each followed by a collapsible that would reveal the highlighted text for the corresponding generated token when opened. 

From my understanding, this should be feasible with the current state of `treescope` but my brief dabbling in `rendering_parts` suggests that a custom variant of [`build_foldable_tree_node_from_children`](https://treescope.readthedocs.io/en/stable/api/leaf/treescope.rendering_parts.build_foldable_tree_node_from_children.html#treescope.rendering_parts.build_foldable_tree_node_from_children) would be needed. In particular, the differences would be:
- Hiding contents from the preview when the collapsible is closed
- Showing the highlighted text as a sequence of `Siblings` on the same row (or with custom word wrapping) rather than the default `IndentedChildren` behavior.

Curious to hear whether a higher-level interface for this could be interesting to add to `treescope` @danieldjohnson

**Comment by danieldjohnson** [comment]
Oh that's a good idea! That's definitely doable with the current system.

Perhaps something like this would do the trick:

```python
def render_input_output_token_value_matrix(tokens, values):
  parts = []
  for i, cur_word in enumerate(tokens):
    subparts = []
    subparts.append(
        treescope.rendering_parts.custom_style(
            treescope.rendering_parts.text(cur_word + ": "),
            css_style="font-style: italic; color: #888888;"
        )
    )
    for j, prev_word in enumerate(tokens[:i]):
      subparts.append(
          treescope.figures.treescope_part_from_display_object(
              treescope.figures.text_on_color(prev_word, value=values[i,j])
          )
      )
    parts.append(
        treescope.rendering_parts.build_full_line_with_annotations(
            treescope.rendering_parts.build_custom_foldable_tree_node(
              label=treescope.rendering_parts.text(cur_word),
              contents=treescope.rendering_parts.fold_condition(
                  collapsed=treescope.rendering_parts.text(" "),
                  expanded=treescope.rendering_parts.indented_children([
                      treescope.rendering_parts.siblings(*subparts)
                  ])
              )
            )
        )
    )

  return treescope.figures.figure_from_treescope_rendering_part(
      treescope.rendering_parts.custom_style(
          treescope.rendering_parts.siblings(*parts),
          css_style="white-space: pre-wrap",
      )
  )
```

Then you could use it like
```python
tokens = "Some example text to demonstrate showing a token matrix with collapsed parts".split(" ")
values = np.random.RandomState(1234).uniform(low=-1, high=0, size=(len(tokens),len(tokens)))
render_input_output_token_value_matrix(tokens, values)
```
![image](https://github.com/user-attachments/assets/3bdf3610-9b45-4a3a-9788-f1fa466cf899)

Is this essentially what you were imagining?

**Comment by gsarti** [comment]
Thanks for the quick reply! That's very close to what I came up with in the end (although I'm not sure if I'm using `treescope` methods properly):

```python
from typing import Any, Sequence

from treescope.figures import treescope_part_from_display_object
from treescope._internal.parts import basic_parts, common_styles, foldable_impl, part_interface
from treescope.rendering_parts import custom_style

class AttributedTokens:
  # 0: Generated token, 1: Attributed token-values for Sequence #1, 2: Attributed token-values for Sequence #2
  def __init__(self, items: Sequence[tuple[str, Sequence[tuple[str, float]] | None, Sequence[tuple[str, float]] | None]]):
    self.items = items

  def __treescope_repr__(self, path, subtree_renderer):
    all_tokens = [custom_style(basic_parts.Text("Generated Tokens"), "font-weight: bold"), basic_parts.Text("\n\n")]
    for item in self.items:
      if item[1] is not None:
        children = [basic_parts.Text("\n\n"), custom_style(basic_parts.Text(f"Source Saliency for Generated Token \"{item[0]}\""), "font-weight: bold"), basic_parts.Text("\n\n")] + [
          treescope_part_from_display_object(treescope.figures.text_on_color(tok, value=val))
          for tok, val in item[1]
        ] + [basic_parts.Text("\n\n")]
      if item[2] is not None:
        children += [custom_style(basic_parts.Text(f"Target Saliency for Generated Token \"{item[0]}\""), "font-weight: bold"), basic_parts.Text("\n\n")] + [
          treescope_part_from_display_object(treescope.figures.text_on_color(tok, value=val))
          for tok, val in item[2]
        ] + [basic_parts.Text("\n\n")]
      curr_tok = foldable_impl.FoldableTreeNodeImpl(
        contents=basic_parts.SummarizableCondition(
          summary=basic_parts.EmptyPart(),
          detail=basic_parts.siblings(*children)
        ),
        label=common_styles.PatternedTopLineSpanGroup(basic_parts.Text(f"{item[0]} ")),
        expand_state=part_interface.ExpandState.COLLAPSED,
      )
      all_tokens.append(curr_tok)
    return basic_parts.RenderableAndLineAnnotations(
      renderable=basic_parts.siblings(*all_tokens),
      annotations=basic_parts.EmptyPart(),
    )
    
AttributedTokens([
    ("Generated", [("Attributed", 0.5), ("Sequence", 0.3), ("#1", 1)], [("Attributed", -1), ("Sequence", 0), ("#2", 0.3)]),
    ("Sequence", [("Attributed", 0.5), ("Sequence", 0.3), ("#1", 1)], None),
    ("#1", [("Attributed", 0.5), ("Sequence", 0.3), ("#1", 1)], [("Attributed", -1), ("Sequence", 0), ("#2", 0.3)])
])
```

Collapsed:

<img width="206" alt="image" src="https://github.com/user-attachments/assets/2bdbaa58-1dad-4a47-8ce7-7e41cdc4596e">

Opened:

<img width="354" alt="image" src="https://github.com/user-attachments/assets/39af473f-a0e2-4919-95bb-c686b35a250f">

This basically solves my problem. Thanks for the help, closing this!

**Comment by danieldjohnson** [comment]
Nice!

One suggestion: I'd advise against directly using the classes in `treescope._internal.parts` since that's a private internal API and may change in the future. It's better to stick to the public API in `treescope.rendering_parts` instead.

> P.S. minor comment: the newlines are currently needed because the score shown on hover is unreadable if the background is not white. Maybe having a white-box background hoverbox similar to the one of rendered array cells could be an option to avoid this issue?

Hm, really? It should already have a white background. (Maybe you can open a separate issue if this isn't working correctly?)
