### ISSUE TITLE
Allow specifying scale in render_array

### ISSUE THREAD

**Issue by marksandler2** [google-deepmind/treescope#9]
It would be nice if render_array would either allow to specify scale (the value that Zoom slider at the bottom controls), as a parameter, or would  automatically adjust scale based on the size of the array and the desired output width.

My use case is that i find it very handy to display fairly large arrays (e.g. 1024x1024 or more), and the initial rendering is way too
big, but adjusting scale to 1 makes it a lot more useful.

![image](https://github.com/user-attachments/assets/8220fe4e-6ace-43f5-b558-f35ebf15d934)

**Comment by danieldjohnson** [comment]
Fixed in release 0.1.3.
